fix attempt
Checkmarx/ast-eclipse-plugin pull request #145
Opened 2024-05-12 13:25 UTC by checkmarx-kobi-hagmi

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](../docs/code_of_conduct.md). Please see the [contributing guidelines](../docs/contributing.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change.

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

2024-05-13 06:56 UTC, AlvoBen approved these changes

2024-05-13 06:57 UTC, AlvoBen commented
Beautiful

2024-05-13 10:42 UTC, OrShamirCM requested changes
add wrapper please

2024-05-15 11:31 UTC, OrShamirCM approved these changes

2024-05-15 12:14 UTC, merged